# Generated by Django 3.0.2 on 2020-01-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(max_length=10)),
                ('Activeusers', models.IntegerField()),
                ('Loggedin', models.IntegerField()),
                ('UserUsage', models.IntegerField()),
                ('Weeknumber', models.IntegerField()),
                ('sno', models.IntegerField()),
            ],
        ),
    ]
