# Generated by Django 3.0.2 on 2020-01-24 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chart',
            new_name='exceldata',
        ),
    ]
