# Generated by Django 3.0.2 on 2020-01-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200124_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='datamonitor',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('organizationName', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('postalAddress', models.CharField(max_length=80)),
                ('fullName', models.CharField(max_length=45)),
                ('emailAddress', models.CharField(max_length=80)),
                ('userCreationDate', models.CharField(max_length=40)),
                ('lastLoginDate', models.CharField(max_length=40)),
                ('loginStatus', models.CharField(max_length=45)),
                ('preferredFileServer', models.CharField(max_length=20)),
                ('auditGroup', models.CharField(max_length=20)),
                ('genericGroup', models.CharField(max_length=10)),
                ('userLastModificationDate', models.CharField(max_length=40)),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'datamonitor',
            },
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='id',
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='exceldata',
            table='exceldata',
        ),
        migrations.CreateModel(
            name='rawdata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('OrganizationName', models.CharField(max_length=45, null=True)),
                ('FullName', models.CharField(max_length=200, null=True)),
                ('EmailAddress', models.CharField(max_length=100, null=True)),
                ('Name', models.CharField(max_length=60)),
                ('PostalAddress', models.CharField(max_length=150, null=True)),
                ('UserCreationDate', models.CharField(max_length=50, null=True)),
                ('LastLoginDate', models.CharField(max_length=50, null=True)),
                ('LoginStatus', models.CharField(max_length=50, null=True)),
                ('PreferredFileServer', models.CharField(max_length=30, null=True)),
                ('AuditGroup', models.CharField(max_length=15, null=True)),
                ('GenericGroup', models.CharField(max_length=15, null=True)),
                ('UserLastModificationDate', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'rawdata',
                'unique_together': {('id', 'Name')},
            },
        ),
    ]
