# Generated by Django 3.0.2 on 2020-02-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200212_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='css_chartview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('org', models.CharField(max_length=12)),
                ('Active', models.IntegerField()),
                ('Loggedin', models.IntegerField()),
                ('Percentage', models.CharField(max_length=5)),
                ('ReportWeek', models.IntegerField()),
                ('ReportYear', models.IntegerField()),
            ],
            options={
                'db_table': 'css_chartview',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Elec_chartview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('org', models.CharField(max_length=12)),
                ('Active', models.IntegerField()),
                ('Loggedin', models.IntegerField()),
                ('Percentage', models.CharField(max_length=5)),
                ('ReportWeek', models.IntegerField()),
                ('ReportYear', models.IntegerField()),
            ],
            options={
                'db_table': 'Elec_chartview',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='lvs_chartview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('org', models.CharField(max_length=12)),
                ('Active', models.IntegerField()),
                ('Loggedin', models.IntegerField()),
                ('Percentage', models.CharField(max_length=5)),
                ('ReportWeek', models.IntegerField()),
                ('ReportYear', models.IntegerField()),
            ],
            options={
                'db_table': 'lvs_chartview',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='oss_chartview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('org', models.CharField(max_length=12)),
                ('Active', models.IntegerField()),
                ('Loggedin', models.IntegerField()),
                ('Percentage', models.CharField(max_length=5)),
                ('ReportWeek', models.IntegerField()),
                ('ReportYear', models.IntegerField()),
            ],
            options={
                'db_table': 'oss_chartview',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='braking_chartview',
        ),
        migrations.AlterModelOptions(
            name='exceldata',
            options={'managed': False},
        ),
    ]
