# Generated by Django 3.0.2 on 2020-02-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='activeusers',
            fields=[
                ('OrganizationName', models.CharField(max_length=45)),
                ('FullName', models.CharField(max_length=200)),
                ('EmailAddress', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=60)),
                ('PostalAddress', models.CharField(max_length=150)),
                ('UserCreationDate', models.CharField(max_length=50)),
                ('LastLoginDate', models.CharField(max_length=50)),
                ('LoginStatus', models.CharField(max_length=50)),
                ('PreferredFileServer', models.CharField(max_length=30)),
                ('AuditGroup', models.CharField(max_length=15)),
                ('GenericGroup', models.CharField(max_length=15)),
                ('UserLastModificationDate', models.CharField(max_length=30)),
                ('ReportWeek', models.IntegerField()),
                ('ReportYear', models.IntegerField()),
            ],
            options={
                'db_table': 'activeusers',
                'managed': False,
                 'unique_together': (('Name', 'ReportWeek','ReportYear','UserCreationDate'),)
            },
        ),
        migrations.CreateModel(
            name='loggedinusers',
            fields=[
                ('EventLabel', models.CharField(max_length=45)),
                ('EventKey', models.CharField(max_length=50)),
                ('EventTime', models.CharField(max_length=50)),
                ('UserName', models.CharField(max_length=100)),
                ('UserID', models.CharField(max_length=60)),
                ('IPAddress', models.CharField(max_length=50)),
                ('UserOrganization', models.CharField(max_length=20)),
                ('ObjectType', models.CharField(max_length=50)),
                ('ObjectID', models.CharField(max_length=50)),
                ('ObjectTypeBranchID', models.CharField(max_length=50)),
                ('ObjectName', models.CharField(max_length=50)),
                ('ObjectNumber', models.CharField(max_length=50)),
                ('BranchID', models.CharField(max_length=50)),
                ('WorkingBranchID', models.CharField(max_length=50)),
                ('Version', models.CharField(max_length=50)),
                ('MasterID', models.CharField(max_length=50)),
                ('OrganizationID', models.CharField(max_length=50)),
                ('OrganizationName', models.CharField(max_length=50)),
                ('ContextID', models.CharField(max_length=50)),
                ('ContextName', models.CharField(max_length=50)),
                ('ContextTypeBranchID', models.CharField(max_length=50)),
                ('FolderPath', models.CharField(max_length=50)),
                ('DomainPath', models.CharField(max_length=50)),
                ('Identity', models.CharField(max_length=50)),
                ('LifecycleState', models.CharField(max_length=45)),
                ('TransactionDescription', models.CharField(max_length=50)),
                ('ObjectIdentity', models.CharField(max_length=50)),
                ('SecurityLabels', models.CharField(max_length=50)),
                ('EventSpecificData', models.CharField(max_length=50)),
                ('ReportWeek', models.IntegerField()),
                ('ReportYear', models.IntegerField()),
            ],
            options={
                'db_table': 'loggedinusers',
                'managed': False,
                'unique_together' : (('EventTime', 'ReportWeek','ReportYear','UserID'),)
            },
        ),
    ]
