# Generated by Django 3.0.2 on 2020-02-25 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_activeusers_loggedinusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='css_chartview',
        ),
        migrations.DeleteModel(
            name='Elec_chartview',
        ),
        migrations.DeleteModel(
            name='lvs_chartview',
        ),
        migrations.DeleteModel(
            name='oss_chartview',
        ),
        migrations.AlterModelOptions(
            name='activeusers',
            options={},
        ),
    ]
