# Generated by Django 3.0.2 on 2020-02-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200225_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exceldata',
            options={},
        ),
        migrations.AddField(
            model_name='activeusers',
            name='id',
            field=models.IntegerField(default=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='activeusers',
            unique_together={('id', 'Name', 'ReportWeek', 'ReportYear', 'UserCreationDate')},
        ),
    ]
